version: '3'

services:
  db:
    image:  kartoza/postgis
  web:
    build: .
    command: python manage.py runserver
    container_name: villastore
    volumes:
      - .:/villastore
    ports:
      - "8000:8000"
    depends_on:
      - db
