version: '3'

services:
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
  db:
    image:  kartoza/postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=user001
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432"

  web:
    build: .
    #    connect gunicorn to wsgi replace the python manage.py runserver 0.0.0.0:8000
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn --timeout=30 --workers=2 --bind :8000 villaStore.wsgi:application"

    container_name: villastore
    volumes:
      - .:/villastore
      - ./static:/static
      - ./media:/media

    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "3000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  postgres_data: