version: '3'

services:
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
  db:
    image:  kartoza/postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=user001
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432"

  web:
    build: .
    command: python manage.py runserver  0.0.0.0:8000
    container_name: villastore
    volumes:
      - .:/villastore
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data: